import Link from "next/link";
import { getAssuranceSnapshot } from "@/lib/assurance-data";

export default function ProofPage() {
  const data = getAssuranceSnapshot();
  return <main className="proof-page">
    <header className="workspace-topbar"><Link href="/" className="wordmark">VERIDIAN</Link><nav><Link href="/workspace">Promise graph</Link><Link href="/checkout">Checkout</Link></nav></header>
    <section className="proof-hero"><span className="proof-kicker">Judge-facing evidence record</span><h1>Proof, without theatre.</h1><p>This page reads the repository&apos;s real requirement, Kane contracts, result folders, evidence registry, and credit ledger. Missing evidence is shown as missing.</p></section>
    <section className="proof-ledger"><article><span>Requirement source</span><h2>{data.source.title}</h2><code>{data.source.path}</code><small>SHA-256 {data.source.hash}</small></article><article><span>Kane assurance depth</span><h2>Ingest → extract → design → testmd → cover</h2><p>The local store contains the trusted source, use case, criteria, and persistent contracts.</p></article><article><span>Browser evidence</span><h2>{data.evidencePacks} recorded runs</h2><p>All three source-linked checkout contracts now pass in real Chrome with fresh sealed evidence.</p></article><article><span>Credit custody</span><h2>{data.ledgerBalance} credits last recorded</h2><p>Every paid recovery run is recorded with its balance, classification, session, and evidence ID.</p></article></section>
    <section className="proof-table"><div className="proof-table-head"><span>Designed contract</span><span>Criteria</span><span>Evidence state</span></div>{data.tests.map(test=><div className="proof-table-row" key={test.file}><div><strong>{test.title}</strong><code>{test.file}</code></div><span>{test.criteria.length || "Mapped"}</span><span className={`status-badge ${test.status.toLowerCase()}`}>{test.status}</span></div>)}</section>
    <section className="proof-table run-table"><div className="proof-table-head"><span>Real Kane session</span><span>Credits</span><span>Verdict</span></div>{data.runs.map(run=><div className="proof-table-row" key={run.sessionId}><div><strong>{run.classification}</strong><code>{run.sessionId} / {run.evidence}</code></div><span>{run.credits.toFixed(4)}</span><span className={`status-badge ${run.status.toLowerCase()}`}>{run.status}</span></div>)}</section>
    {data.valueCycle && <section className="proof-callout"><div><span className="proof-kicker">Value-checking proof cycle</span><h2>Kane caught the discount calculation bug.</h2><p>SAVE20 displayed its discount, but the charged total remained <strong>{data.valueCycle.actual}</strong> instead of <strong>{data.valueCycle.expected}</strong>. The agent repaired <code>src/lib/checkout.ts</code> with one calculation-line change. The unchanged contract hash is <code>{data.valueCycle.contractHash}</code>.</p><p>Baseline <code>{data.valueCycle.baselineSession}</code> â†’ product failure <code>{data.valueCycle.failureSession}</code> â†’ repaired replay <code>{data.valueCycle.repairSession}</code>. {data.valueCycle.repairStatus}</p></div><Link href="/workspace" className="button primary">Trace the promise</Link></section>}
    <section className="proof-callout"><div><span className="proof-kicker">Honest release state</span><h2>{data.coverage.proven}/{data.coverage.designed} acceptance criteria proven.</h2><p>Kane still reports 100% coverage for the source-linked assurance graph. The added focused contract independently proves the arithmetic regression; its repaired value assertion passes, while its final confirmation check is transparently recorded as locator drift.</p></div><Link href="/checkout" className="button primary">Open verification target</Link></section>
  </main>;
}
